"""Export generated test suites to standard testing frameworks.

Supports:
  - Python: pytest with @pytest.mark.parametrize and descriptive assertions
  - Python: unittest.TestCase test suite
  - Java: JUnit 5 test class
  - C++: Google Test (gtest) TEST fixtures
  - Structured: JSON and CSV
"""

from __future__ import annotations

import csv
import io
import json
from typing import Any, Dict, List

from schemas import StudentTestSuite, TestCase


def export_to_pytest(suites: List[Dict[str, Any]], entry_function: str = "solution") -> str:
    """Generate runnable pytest test file from test suite."""
    lines = [
        '"""Automatically generated by SpecTest-LLM."""',
        "import pytest",
        f"from solution import {entry_function}",
        "",
    ]

    flat_cases: List[Dict[str, Any]] = []
    for s in suites:
        flat_cases.extend(s.get("cases", []))

    for idx, c in enumerate(flat_cases, start=1):
        cid = c.get("id", f"case_{idx}").replace("-", "_")
        cat = c.get("category", "General")
        desc = c.get("explanation", "").replace('"', '\\"').replace("\n", " ")
        inp = c.get("input")
        expected = c.get("expected")

        lines.append(f"# [{cat}] {desc}")
        lines.append(f"def test_{cid}():")
        lines.append(f'    """Category: {cat} - {desc}"""')

        if isinstance(inp, list):
            args_str = ", ".join(repr(arg) for arg in inp)
            lines.append(f"    assert {entry_function}({args_str}) == {repr(expected)}")
        elif isinstance(inp, dict):
            kwargs_str = ", ".join(f"{k}={repr(v)}" for k, v in inp.items())
            lines.append(f"    assert {entry_function}({kwargs_str}) == {repr(expected)}")
        else:
            lines.append(f"    assert {entry_function}({repr(inp)}) == {repr(expected)}")
        lines.append("")

    return "\n".join(lines)


def export_to_unittest(suites: List[Dict[str, Any]], entry_function: str = "solution") -> str:
    """Generate runnable Python unittest file."""
    lines = [
        '"""Automatically generated by SpecTest-LLM."""',
        "import unittest",
        f"from solution import {entry_function}",
        "",
        "class SpecTestLLMSuite(unittest.TestCase):",
    ]

    flat_cases: List[Dict[str, Any]] = []
    for s in suites:
        flat_cases.extend(s.get("cases", []))

    for idx, c in enumerate(flat_cases, start=1):
        cid = c.get("id", f"case_{idx}").replace("-", "_")
        cat = c.get("category", "General")
        desc = c.get("explanation", "").replace('"', '\\"')
        inp = c.get("input")
        expected = c.get("expected")

        lines.append(f"    def test_{cid}(self):")
        lines.append(f'        """[{cat}] {desc}"""')
        if isinstance(inp, list):
            args_str = ", ".join(repr(arg) for arg in inp)
            lines.append(f"        self.assertEqual({entry_function}({args_str}), {repr(expected)})")
        elif isinstance(inp, dict):
            kwargs_str = ", ".join(f"{k}={repr(v)}" for k, v in inp.items())
            lines.append(f"        self.assertEqual({entry_function}({kwargs_str}), {repr(expected)})")
        else:
            lines.append(f"        self.assertEqual({entry_function}({repr(inp)}), {repr(expected)})")
        lines.append("")

    lines.extend([
        "if __name__ == '__main__':",
        "    unittest.main()",
        "",
    ])
    return "\n".join(lines)


def export_to_junit(suites: List[Dict[str, Any]], class_name: str = "Solution") -> str:
    """Generate JUnit 5 Java test class."""
    lines = [
        "// Automatically generated by SpecTest-LLM",
        "import org.junit.jupiter.api.Test;",
        "import org.junit.jupiter.api.DisplayName;",
        "import static org.junit.jupiter.api.Assertions.*;",
        "",
        f"public class {class_name}Test {{",
    ]

    flat_cases: List[Dict[str, Any]] = []
    for s in suites:
        flat_cases.extend(s.get("cases", []))

    for idx, c in enumerate(flat_cases, start=1):
        cid = c.get("id", f"case_{idx}").replace("-", "_")
        cat = c.get("category", "General")
        desc = c.get("explanation", "").replace('"', '\\"')
        inp = json.dumps(c.get("input"))
        exp = json.dumps(c.get("expected"))

        lines.append(f'    @Test')
        lines.append(f'    @DisplayName("[{cat}] {desc}")')
        lines.append(f'    void test_{cid}() {{')
        lines.append(f'        // Input: {inp}')
        lines.append(f'        // Expected: {exp}')
        lines.append(f'        // assertEquals({exp}, {class_name}.solve({inp}));')
        lines.append(f'    }}')
        lines.append("")

    lines.append("}")
    return "\n".join(lines)


def export_to_gtest(suites: List[Dict[str, Any]], test_fixture: str = "SolutionTest") -> str:
    """Generate C++ Google Test file."""
    lines = [
        "// Automatically generated by SpecTest-LLM",
        '#include <gtest/gtest.h>',
        '#include "solution.h"',
        "",
    ]

    flat_cases: List[Dict[str, Any]] = []
    for s in suites:
        flat_cases.extend(s.get("cases", []))

    for idx, c in enumerate(flat_cases, start=1):
        cid = c.get("id", f"case_{idx}").replace("-", "_")
        cat = c.get("category", "General")
        desc = c.get("explanation", "").replace('"', '\\"')
        inp = json.dumps(c.get("input"))
        exp = json.dumps(c.get("expected"))

        lines.append(f'// [{cat}] {desc}')
        lines.append(f'TEST({test_fixture}, {cid}) {{')
        lines.append(f'    // Input: {inp}')
        lines.append(f'    // Expected: {exp}')
        lines.append(f'    // EXPECT_EQ(solve({inp}), {exp});')
        lines.append(f'}}')
        lines.append("")

    return "\n".join(lines)


def export_to_csv(suites: List[Dict[str, Any]]) -> str:
    """Export test cases to CSV."""
    out = io.StringIO()
    writer = csv.writer(out)
    writer.writerow(["id", "student_id", "category", "input", "expected", "oracle_match", "discrimination", "explanation"])

    for s in suites:
        sid = s.get("student_id", 1)
        for c in s.get("cases", []):
            writer.writerow([
                c.get("id", ""),
                sid,
                c.get("category", ""),
                json.dumps(c.get("input")),
                json.dumps(c.get("expected")),
                c.get("oracle_match", ""),
                c.get("discrimination_score", ""),
                c.get("explanation", ""),
            ])

    return out.getvalue()
